In [38]:
import pandas as pd
import numpy as np

In [39]:
data=pd.read_csv("spam.csv")
data.head(5)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [40]:
data['spam'] =data['Category'].apply(lambda x: 1 if x=='spam' else 0)
data.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.Message,data.spam,train_size=.8)

In [42]:
from sklearn.feature_extraction.text import  CountVectorizer
v=CountVectorizer()

xtrainCount= v.fit_transform(X_train.values)
xtrainCount.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model


MultinomialNB()

In [44]:
model.fit(xtrainCount,y_train)

MultinomialNB()

In [45]:
model.score(v.transform(X_test),y_test)

0.9874439461883409

In [46]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

# by pipline directly


In [47]:
from sklearn.pipeline import Pipeline

pip=Pipeline([
    ('vector',CountVectorizer()),
    ('mp',MultinomialNB()),
])
pip.fit(X_train,y_train)

Pipeline(steps=[('vector', CountVectorizer()), ('mp', MultinomialNB())])

In [48]:
pip.score(X_test,y_test)

0.9874439461883409

In [49]:
pip.predict(emails)

array([0, 1], dtype=int64)