In [45]:
from sklearn.datasets import load_iris
iris=load_iris()

In [46]:
import pandas as pd
import numpy as np

data=pd.DataFrame(iris.data,columns=iris.feature_names)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [47]:
data['target']=iris.target
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

## 1 Approch in Train test split

In [48]:
from sklearn.model_selection import train_test_split

Xtrain,Xtest,Ytrain,Ytest=train_test_split(data.drop(['target'],axis=1),data['target'],train_size=.8)


In [49]:
from sklearn.svm import SVC
svc=SVC(C=10,kernel='rbf')
svc.fit(Xtrain,Ytrain)
svc.score(Xtest,Ytest)

0.9666666666666667

## 2  K fold Cross Validation

In [50]:
X=data.drop(['target'],axis=1)
Y=data['target']


In [51]:
from sklearn.model_selection import cross_val_score

c =cross_val_score(SVC(C=10,kernel='rbf',gamma='auto'),X,Y,cv=5)
c

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [52]:
c =cross_val_score(SVC(C=20,kernel='linear',gamma='auto'),X,Y,cv=5)
c

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [53]:
c =cross_val_score(SVC(C=1,kernel='linear',gamma='auto'),X,Y,cv=5)
c

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [54]:
kernel=['linear', 'poly', 'rbf',]
c=[1,10,20,30]
avg_scores={}
for k in kernel:
    for cc in c:
        cvScore= cross_val_score(SVC(C=cc,kernel=k,gamma='auto'),X,Y,cv=5)
        avg_scores[k + '_' + str(cc)] = np.average(cvScore)

avg_scores

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96,
 'poly_1': 0.9666666666666666,
 'poly_10': 0.9666666666666666,
 'poly_20': 0.9533333333333334,
 'poly_30': 0.9533333333333334,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96}

## 3 use   GridsearchCV

In [55]:
from sklearn.model_selection import GridSearchCV

clf=GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20,30],
    'kernel':['linear', 'poly', 'rbf',]
}, cv=5,return_train_score=False
)
clf.fit(X,Y)
clf.cv_results_
d=pd.DataFrame(clf.cv_results_)
d

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.002003      0.000897         0.001206        0.000431       1   
1        0.002605      0.001005         0.001006        0.000013       1   
2        0.001589      0.000483         0.001005        0.000016       1   
3        0.001402      0.000498         0.000997        0.000001      10   
4        0.003789      0.001724         0.001396        0.000486      10   
5        0.001590      0.000484         0.001197        0.000400      10   
6        0.001396      0.000490         0.000998        0.000002      20   
7        0.006595      0.004494         0.000985        0.000015      20   
8        0.001595      0.000490         0.000997        0.000020      20   
9        0.001193      0.000403         0.001002        0.000015      30   
10       0.006384      0.004166         0.001198        0.000382      30   
11       0.001398      0.000489         0.001189        0.000386      30   

   param_kernel                         params  split0_test_score  \
0        linear   {'C': 1, 'kernel': 'linear'}           0.966667   
1          poly     {'C': 1, 'kernel': 'poly'}           1.000000   
2           rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
3        linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          poly    {'C': 10, 'kernel': 'poly'}           1.000000   
5           rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
6        linear  {'C': 20, 'kernel': 'linear'}           1.000000   
7          poly    {'C': 20, 'kernel': 'poly'}           0.966667   
8           rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
9        linear  {'C': 30, 'kernel': 'linear'}           1.000000   
10         poly    {'C': 30, 'kernel': 'poly'}           0.966667   
11          rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   

    split1_test_score  split2_test_score  split3_test_score  \
0            1.000000           0.966667           0.966667   
1            1.000000           0.900000           0.933333   
2            1.000000           0.966667           0.966667   
3            1.000000           0.900000           0.966667   
4            1.000000           0.900000           0.933333   
5            1.000000           0.966667           0.966667   
6            1.000000           0.900000           0.933333   
7            0.966667           0.900000           0.933333   
8            1.000000           0.900000           0.966667   
9            1.000000           0.900000           0.900000   
10           0.966667           0.900000           0.933333   
11           1.000000           0.900000           0.933333   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                 1.0         0.980000        0.016330                1  
1                 1.0         0.966667        0.042164                6  
2                 1.0         0.980000        0.016330                1  
3                 1.0         0.973333        0.038873                4  
4                 1.0         0.966667        0.042164                6  
5                 1.0         0.980000        0.016330                1  
6                 1.0         0.966667        0.042164                6  
7                 1.0         0.953333        0.033993               11  
8                 1.0         0.966667        0.036515                5  
9                 1.0         0.960000        0.048990                9  
10                1.0         0.953333        0.033993               11  
11                1.0         0.960000        0.038873                9

In [56]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [57]:
pd.DataFrame(clf.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1         poly         0.966667
2        1          rbf         0.980000
3       10       linear         0.973333
4       10         poly         0.966667
5       10          rbf         0.980000
6       20       linear         0.966667
7       20         poly         0.953333
8       20          rbf         0.966667
9       30       linear         0.960000
10      30         poly         0.953333
11      30          rbf         0.960000

# Main Example 

In [58]:
# import models
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [59]:
# dic of models and params

model_params={
    'SVC':{
        'model':SVC(gamma='auto'),
        'params':{
            'C':[1,10,20,30],
            'kernel':['linear', 'poly', 'rbf',]
        }
    },
    'RandomForestClassifier':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[5,10,15,20,30,40,50,],
            'criterion':["gini", "entropy"]
        }
    },
    "LogisticRegression":{
        'model':LogisticRegression(),
        'params':{
            'C':[1,5,10,15]
        }
    }
}

In [60]:
scores=[]
for mn,mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'], cv=5,return_train_score=False)
    clf.fit(X,Y)
    scores.append({
        'modelName':mn,
        'bestParams':clf.best_params_,
        'bestScore':clf.best_score_
    })

scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

[{'modelName': 'SVC',
  'bestParams': {'C': 1, 'kernel': 'linear'},
  'bestScore': 0.9800000000000001},
 {'modelName': 'RandomForestClassifier',
  'bestParams': {'criterion': 'gini', 'n_estimators': 10},
  'bestScore': 0.9600000000000002},
 {'modelName': 'LogisticRegression',
  'bestParams': {'C': 10},
  'bestScore': 0.9800000000000001}]

In [62]:
df = pd.DataFrame(scores)
df

modelName                                 bestParams  \
0                     SVC               {'C': 1, 'kernel': 'linear'}   
1  RandomForestClassifier  {'criterion': 'gini', 'n_estimators': 10}   
2      LogisticRegression                                  {'C': 10}   

   bestScore  
0       0.98  
1       0.96  
2       0.98