In [3]:
import numpy as np 
from sklearn.datasets import load_digits
import pandas as pd
digit=load_digits()
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
data=digit.data
df=pd.DataFrame(data,columns=digit.feature_names)
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [7]:
df['target']= digit.target
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [9]:
from sklearn.model_selection import train_test_split
y=df['target']
xtrain,xtest,ytrain,ytest=train_test_split(df.drop(['target'],axis=1),y,test_size=.8)


## linearRegression


In [10]:
from sklearn.linear_model import LinearRegression

modelLin=LinearRegression()
modelLin.fit(xtrain,ytrain)
modelLin.score(xtest,ytest)

0.47896314227330705

## logistic 

In [11]:
from sklearn.linear_model import LogisticRegression

modelLog=LinearRegression()
modelLog.fit(xtrain,ytrain)
modelLog.score(xtest,ytest)

0.47896314227330705

In [12]:
from sklearn.tree import DecisionTreeClassifier

modelTree=DecisionTreeClassifier()
modelTree.fit(xtrain,ytrain)
modelTree.score(xtest,ytest)

0.760778859527121

In [13]:
from sklearn.svm import SVC

modelscv=SVC()
modelscv.fit(xtrain,ytrain)
modelscv.score(xtest,ytest)

0.9735744089012517

In [15]:
from sklearn.ensemble import RandomForestClassifier

modelforest=RandomForestClassifier(n_estimators=10)
modelforest.fit(xtrain,ytrain)
modelforest.score(xtest,ytest)

0.8963838664812239

In [18]:
from sklearn.model_selection import KFold

kfold=KFold(n_splits=4)
kfold

KFold(n_splits=4, random_state=None, shuffle=False)

In [19]:
for  trainindex , textindex in kfold.split([1,2,3,4,5,6,7,8,9]):
    print(trainindex,textindex)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [23]:
def get_scour(model,xtrain,xtest,ytrain,ytest):
    model.fit(xtrain,ytrain)
    return model.score(xtest,ytest)


In [24]:
get_scour(LinearRegression(),xtrain,xtest,ytrain,ytest)

0.47896314227330705

In [25]:
get_scour(SVC(),xtrain,xtest,ytrain,ytest)

0.9735744089012517

In [26]:
get_scour(DecisionTreeClassifier(),xtrain,xtest,ytrain,ytest)

0.7579972183588317

In [33]:
get_scour(RandomForestClassifier(n_estimators=50),xtrain,xtest,ytrain,ytest)

0.9506258692628651

In [29]:
get_scour(LogisticRegression(),xtrain,xtest,ytrain,ytest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9499304589707928

In [35]:
from sklearn.model_selection import cross_val_score


In [36]:
cross_val_score(LogisticRegression(),xtrain,ytrain,cv=3)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.94166667, 0.93333333, 0.94957983])

In [37]:
cross_val_score(LinearRegression(),xtrain,ytrain,cv=3)

array([-1.07836401e+21,  3.42480438e-01,  5.32934518e-01])

In [38]:
cross_val_score(SVC(),xtrain,ytrain,cv=3)

array([0.95      , 0.95      , 0.94957983])